export interface DocumentationEntry {
  slug: string;
  title: string;
  section: 'Introduction' | 'Packages' | 'Core Package' | 'Angular Package' | 'React' | 'React Package' | 'Vanilla Showcase' | 'Guides' | 'Reference' | 'Project';
  summary: string;
  source: string;
  showcasePath?: string;
  navGroup?: 'State Management';
}

export const documentationCatalog: DocumentationEntry[] = [
  { slug: 'overview', title: 'What is Validation Rules Engine (VRE)?', section: 'Introduction', summary: 'Validation Rules Engine (VRE), its purpose, philosophy, and platform packages.', source: 'overview.md' },
  { slug: 'getting-started', title: 'Installation & Quick Start', section: 'Introduction', summary: 'Install, configure, register, and run your first policy.', source: 'getting-started.md' },
  { slug: 'core-package', title: 'Overview', section: 'Core Package', summary: 'Framework-neutral contracts, validators, and model state.', source: 'core/core-package.md', showcasePath: '/' },
  { slug: 'core-installation', title: 'Installation', section: 'Core Package', summary: 'Install the framework-neutral package and understand peer boundaries.', source: 'core/core-installation.md', showcasePath: '/' },
  { slug: 'core-quick-start', title: 'Quick Start', section: 'Core Package', summary: 'Create a model, policy, helper, and validation result flow in TypeScript.', source: 'core/core-quick-start.md', showcasePath: '/simple' },
  { slug: 'core-architecture', title: 'Architecture', section: 'Core Package', summary: 'How policies, validators, helpers, groups, and metadata fit together.', source: 'core/core-architecture.md', showcasePath: '/' },
  { slug: 'core-validation-policies', title: 'Validation Policies', section: 'Core Package', summary: 'Compose reusable policy classes and register them from adapters.', source: 'core/core-validation-policies.md', showcasePath: '/simple' },
  { slug: 'core-validation-rules', title: 'Validation Rules', section: 'Core Package', summary: 'Built-in rule behavior, optional fields, custom rules, and execution order.', source: 'core/core-validation-rules.md', showcasePath: '/simple' },
  { slug: 'core-validation-groups', title: 'Validation Groups', section: 'Core Package', summary: 'Group policies, form groups, and result summaries at logical boundaries.', source: 'core/core-validation-groups.md', showcasePath: '/complex' },
  { slug: 'core-public-api', title: 'Public API', section: 'Core Package', summary: 'Supported Core exports, interfaces, and intended usage.', source: 'core/core-public-api.md', showcasePath: '/' },
  { slug: 'core-examples', title: 'Examples', section: 'Core Package', summary: 'Complete TypeScript examples for nested models, groups, and custom rules.', source: 'core/core-examples.md', showcasePath: '/complex' },
  { slug: 'core-best-practices', title: 'Best Practices', section: 'Core Package', summary: 'Policy design, naming, model ownership, performance, and testing guidance.', source: 'core/core-best-practices.md', showcasePath: '/performance' },
  { slug: 'core-troubleshooting', title: 'Troubleshooting', section: 'Core Package', summary: 'Diagnose paths, optional rules, dependency expressions, and stale results.', source: 'core/core-troubleshooting.md', showcasePath: '/simple' },
  { slug: 'core-faq', title: 'FAQ', section: 'Core Package', summary: 'Common Core package design and usage questions.', source: 'core/core-faq.md', showcasePath: '/' },
  { slug: 'angular', title: 'Overview', section: 'Angular Package', summary: 'Angular lifecycle, registration, directives, and display.', source: 'angular/angular.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-installation', title: 'Installation', section: 'Angular Package', summary: 'Install Angular dependencies and wire provider configuration.', source: 'angular/angular-installation.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-quick-start', title: 'Quick Start', section: 'Angular Package', summary: 'Build a policy-backed ngModel form with inline messages.', source: 'angular/angular-quick-start.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-architecture', title: 'Architecture', section: 'Angular Package', summary: 'How Angular services, directives, components, and Core policies collaborate.', source: 'angular/angular-architecture.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-services', title: 'Services', section: 'Angular Package', summary: 'ValidationProviderService, policy registration, groups, and refresh behavior.', source: 'angular/angular-services.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-components', title: 'Components', section: 'Angular Package', summary: 'Message, summary, group status, and display components.', source: 'angular/angular-components.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-directives', title: 'Directives', section: 'Angular Package', summary: 'policyValidator, model paths, touched state, and display strategies.', source: 'angular/angular-directives.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-validation-policies', title: 'Validation Policies', section: 'Angular Package', summary: 'Create Angular-facing policies that remain Core-compatible.', source: 'angular/angular-validation-policies.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-validation-groups', title: 'Validation Groups', section: 'Angular Package', summary: 'Register, validate, and display grouped sections in Angular forms.', source: 'angular/angular-validation-groups.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-ngmodel', title: 'Template Driven Forms', section: 'Angular Package', summary: 'Template-driven form binding with policy validation.', source: 'angular/angular-ngmodel.md', showcasePath: '/state/template-driven', navGroup: 'State Management' },
  { slug: 'angular-reactive-forms', title: 'Reactive Forms', section: 'Angular Package', summary: 'Coordinate Reactive Forms and policy validation in enterprise workflows.', source: 'angular/angular-reactive-forms.md', showcasePath: '/state/reactive-forms', navGroup: 'State Management' },
  { slug: 'angular-state-ngrx', title: 'NgRx', section: 'Angular Package', summary: 'Action, reducer, and selector-based Angular state validation.', source: 'angular/angular-state-ngrx.md', showcasePath: '/state/ngrx', navGroup: 'State Management' },
  { slug: 'angular-state-ngxs', title: 'NGXS', section: 'Angular Package', summary: 'Class-based Angular state handlers with policy validation.', source: 'angular/angular-state-ngxs.md', showcasePath: '/state/ngxs', navGroup: 'State Management' },
  { slug: 'angular-state-akita', title: 'Akita', section: 'Angular Package', summary: 'Store and Query-based Angular validation state integration.', source: 'angular/angular-state-akita.md', showcasePath: '/state/akita', navGroup: 'State Management' },
  { slug: 'angular-state-elf', title: 'Elf', section: 'Angular Package', summary: 'Lightweight Elf stores with Validation Rules Engine snapshots.', source: 'angular/angular-state-elf.md', showcasePath: '/state/elf', navGroup: 'State Management' },
  { slug: 'angular-state-rx-angular', title: 'RxAngular State', section: 'Angular Package', summary: 'Component-scoped RxAngular State with policy validation.', source: 'angular/angular-state-rx-angular.md', showcasePath: '/state/rx-angular-state', navGroup: 'State Management' },
  { slug: 'angular-state-signals', title: 'Signals', section: 'Angular Package', summary: 'Angular Signal-backed validation model snapshots.', source: 'angular/angular-state-signals.md', showcasePath: '/state/signals', navGroup: 'State Management' },
  { slug: 'angular-state-custom-rxjs-store', title: 'Custom RxJS Store', section: 'Angular Package', summary: 'BehaviorSubject-backed feature stores and validation results.', source: 'angular/angular-state-custom-rxjs-store.md', showcasePath: '/state/custom-rxjs-store', navGroup: 'State Management' },
  { slug: 'angular-examples', title: 'Examples', section: 'Angular Package', summary: 'Complete template-driven, reactive, dynamic, and custom component examples.', source: 'angular/angular-examples.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-best-practices', title: 'Best Practices', section: 'Angular Package', summary: 'Lifecycle, performance, display strategy, and test guidance.', source: 'angular/angular-best-practices.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-troubleshooting', title: 'Troubleshooting', section: 'Angular Package', summary: 'Common Angular setup, directive, path, and display problems.', source: 'angular/angular-troubleshooting.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'angular-faq', title: 'FAQ', section: 'Angular Package', summary: 'Common Angular adapter questions.', source: 'angular/angular-faq.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'react-overview', title: 'Overview', section: 'React Package', summary: 'Hooks-first adapter capabilities and package boundaries.', source: 'react/react-overview.md', showcasePath: '/' },
  { slug: 'react-installation', title: 'Installation', section: 'React Package', summary: 'Install React peers and verify workspace compatibility.', source: 'react/react-installation.md', showcasePath: '/' },
  { slug: 'react-quick-start', title: 'Quick Start', section: 'React Package', summary: 'Build a provider-backed controlled form with a core policy.', source: 'react/react-quick-start.md', showcasePath: '/state/local-state/simple' },
  { slug: 'react-architecture', title: 'Architecture', section: 'React Package', summary: 'Engine ownership, dependency direction, and model state.', source: 'react/react-architecture.md', showcasePath: '/' },
  { slug: 'react-provider', title: 'Provider', section: 'React Package', summary: 'Provider configuration, engine ownership, nesting, SSR, and cleanup.', source: 'react/react-provider.md', showcasePath: '/' },
  { slug: 'react-hooks', title: 'Core Hooks', section: 'React Package', summary: 'Signatures and lifecycle for every public React hook.', source: 'react/react-hooks.md', showcasePath: '/state/local-state/simple' },
  { slug: 'react-field-validation', title: 'Field Validation', section: 'React Package', summary: 'Focused errors, touch/dirty state, blur, change, and ARIA props.', source: 'react/react-field-validation.md', showcasePath: '/state/local-state/simple' },
  { slug: 'react-form-validation', title: 'Form Validation', section: 'React Package', summary: 'Submit, validate-all, reset, summaries, and programmatic workflows.', source: 'react/react-form-validation.md', showcasePath: '/state/local-state/simple' },
  { slug: 'react-policies', title: 'Validation Policies', section: 'React Package', summary: 'Create, register, replace, and clean up one or more policies.', source: 'react/react-policies.md', showcasePath: '/state/local-state/complex' },
  { slug: 'react-groups', title: 'Validation Groups', section: 'React Package', summary: 'Define, switch, validate, and display grouped state.', source: 'react/react-groups.md', showcasePath: '/state/local-state/complex' },
  { slug: 'react-state-local-state', title: 'Local State', section: 'React Package', summary: 'useState and useReducer model ownership with the shared validation lifecycle.', source: 'react/react-state-local-state.md', showcasePath: '/state/local-state', navGroup: 'State Management' },
  { slug: 'react-state-redux-toolkit', title: 'Redux Toolkit', section: 'React Package', summary: 'Slices, actions, selectors, and a serializable Redux form model.', source: 'react/react-state-redux-toolkit.md', showcasePath: '/state/redux-toolkit', navGroup: 'State Management' },
  { slug: 'react-state-zustand', title: 'Zustand', section: 'React Package', summary: 'A scoped external store, actions, and focused Zustand selectors.', source: 'react/react-state-zustand.md', showcasePath: '/state/zustand', navGroup: 'State Management' },
  { slug: 'react-state-jotai', title: 'Jotai', section: 'React Package', summary: 'Primitive and derived atoms connected to validation hooks.', source: 'react/react-state-jotai.md', showcasePath: '/state/jotai', navGroup: 'State Management' },
  { slug: 'react-state-recoil', title: 'Recoil', section: 'React Package', summary: 'Atoms and selectors for existing Recoil applications, including React 19 compatibility notes.', source: 'react/react-state-recoil.md', showcasePath: '/state/recoil', navGroup: 'State Management' },
  { slug: 'react-state-mobx', title: 'MobX', section: 'React Package', summary: 'Observable state, computed values, actions, and an observer bridge.', source: 'react/react-state-mobx.md', showcasePath: '/state/mobx', navGroup: 'State Management' },
  { slug: 'react-state-context', title: 'Context API', section: 'React Package', summary: 'A built-in Context Provider, reducer, and consumer bridge.', source: 'react/react-state-context.md', showcasePath: '/state/context', navGroup: 'State Management' },
  { slug: 'react-controlled-inputs', title: 'Controlled Inputs', section: 'React Package', summary: 'Native input, checkbox, select, and controlled-state patterns.', source: 'react/react-controlled-inputs.md', showcasePath: '/state/local-state/simple' },
  { slug: 'react-custom-components', title: 'Custom Inputs', section: 'React Package', summary: 'Integrate design-system controls without adapter-owned styling.', source: 'react/react-custom-components.md', showcasePath: '/state/local-state/complex' },
  { slug: 'react-dynamic-fields', title: 'Dynamic Fields', section: 'React Package', summary: 'Arrays, conditional sections, and dynamically generated policies.', source: 'react/react-dynamic-fields.md', showcasePath: '/state/local-state/complex' },
  { slug: 'react-multiple-forms', title: 'Multiple Forms', section: 'React Package', summary: 'Independent models, providers, policies, and page contexts.', source: 'react/react-multiple-forms.md', showcasePath: '/state/local-state/complex' },
  { slug: 'react-performance', title: 'Performance', section: 'React Package', summary: 'Stable policy inputs, focused validation, measurement, and render guidance.', source: 'react/react-performance.md', showcasePath: '/state/local-state/performance' },
  { slug: 'react-strict-mode', title: 'Strict Mode', section: 'React Package', summary: 'Reference-counted registration and effect cleanup behavior.', source: 'react/react-strict-mode.md', showcasePath: '/' },
  { slug: 'react-testing', title: 'Testing', section: 'React Package', summary: 'Test provider, hooks, controls, async rules, and Strict Mode.', source: 'react/react-testing.md', showcasePath: '/state/local-state/simple' },
  { slug: 'react-api', title: 'Public API', section: 'React Package', summary: 'Complete supported exports, parameters, and return values.', source: 'react/react-api.md', showcasePath: '/' },
  { slug: 'react-migration', title: 'Migration and Compatibility', section: 'React Package', summary: 'React 19.2 compatibility and migration from manual core orchestration.', source: 'react/react-migration.md', showcasePath: '/' },
  { slug: 'react-examples', title: 'Examples', section: 'React Package', summary: 'Direct links to simple, complex, and performance React examples.', source: 'react/react-examples.md', showcasePath: '/state/local-state' },
  { slug: 'react-best-practices', title: 'Best Practices', section: 'React Package', summary: 'Policy, hook, state ownership, custom input, and performance guidance.', source: 'react/react-best-practices.md', showcasePath: '/state/local-state' },
  { slug: 'react-troubleshooting', title: 'Troubleshooting', section: 'React Package', summary: 'Diagnose provider, policy, path, controlled-input, and async issues.', source: 'react/react-troubleshooting.md', showcasePath: '/' },
  { slug: 'react-faq', title: 'FAQ', section: 'React Package', summary: 'Common React adapter and state integration questions.', source: 'react/react-faq.md', showcasePath: '/' },
  { slug: 'vanilla-overview', title: 'Overview', section: 'Vanilla Showcase', summary: 'Framework-free TypeScript showcase that consumes Core directly.', source: 'vanilla/vanilla-overview.md', showcasePath: '/' },
  { slug: 'vanilla-quick-start', title: 'Quick Start', section: 'Vanilla Showcase', summary: 'Install Core and validate plain TypeScript models without an adapter.', source: 'vanilla/vanilla-quick-start.md', showcasePath: '/simple' },
  { slug: 'vanilla-examples', title: 'Examples', section: 'Vanilla Showcase', summary: 'Simple, complex, and performance Vanilla Showcase routes.', source: 'vanilla/vanilla-examples.md', showcasePath: '/' },
  { slug: 'policies-and-rules', title: 'Policies & Rules', section: 'Guides', summary: 'Compose rule sets and understand execution behavior.', source: 'policies-and-rules.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'validation-groups', title: 'Validation Groups', section: 'Guides', summary: 'Field groups, policy groups, status, and summaries.', source: 'validation-groups.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'advanced', title: 'Advanced Examples', section: 'Guides', summary: 'Conditional, asynchronous, nested, and dynamic workflows.', source: 'advanced.md', showcasePath: '/showcases/bootstrap' },
  { slug: 'public-api', title: 'Public API Reference', section: 'Reference', summary: 'Supported public types, services, and methods.', source: 'public-api.md' },
  { slug: 'architecture', title: 'Architecture', section: 'Project', summary: 'Dependency boundaries, application registry, and build order.', source: 'architecture.md' },
  { slug: 'single-host-deployment', title: 'Single-Host Deployment', section: 'Project', summary: 'Build and deploy the portal, docs, showcases, reports, and automation under one origin.', source: 'single-host-deployment.md' },
  { slug: 'release-versioning', title: 'Release & Versioning', section: 'Project', summary: 'Synchronized Semantic Versioning, quality gates, package previews, and npm publishing.', source: 'release-versioning.md' },
  { slug: 'testing', title: 'Testing, Coverage & Reports', section: 'Project', summary: 'Test commands, coverage gates, and persistent reports.', source: 'testing.md' },
  { slug: 'playwright', title: 'Playwright E2E Testing', section: 'Project', summary: 'Repository-level browser automation, reports, accessibility, visual checks, and portal integration.', source: 'playwright.md' },
  { slug: 'migration', title: 'Migration', section: 'Project', summary: 'Package boundaries and migration guidance.', source: 'migration.md' },
  { slug: 'roadmap', title: 'Roadmap', section: 'Project', summary: 'Planned platform and adapter directions without placeholder implementations.', source: 'roadmap.md' },
  { slug: 'troubleshooting', title: 'Troubleshooting', section: 'Project', summary: 'Common setup, validation, display, and report issues.', source: 'troubleshooting.md' },
  { slug: 'faq', title: 'FAQ', section: 'Project', summary: 'Frequently asked design and usage questions.', source: 'faq.md' }
];

export function documentationEntry(slug: string): DocumentationEntry | undefined {
  return documentationCatalog.find((entry) => entry.slug === slug);
}
