import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const workspaceRoot = process.cwd();
const distRoot = path.join(workspaceRoot, 'dist');
const siteRoot = path.join(distRoot, 'site');

if (path.dirname(siteRoot) !== distRoot || path.basename(siteRoot) !== 'site') {
  throw new Error(`Refusing to rebuild an unexpected site directory: ${siteRoot}`);
}

const requiredDirectories = [
  path.join(workspaceRoot, 'apps', 'portal', 'public'),
  path.join(workspaceRoot, 'apps', 'docs', 'public'),
  path.join(workspaceRoot, 'tools', 'platform-shell'),
  path.join(distRoot, 'apps', 'docs'),
  path.join(distRoot, 'showcases', 'angular'),
  path.join(distRoot, 'showcases', 'react'),
  path.join(distRoot, 'showcases', 'vanilla')
];

for (const directory of requiredDirectories) {
  if (!existsSync(directory)) {
    throw new Error(`Required hosted application output is missing: ${directory}`);
  }
}

rmSync(siteRoot, { recursive: true, force: true });
mkdirSync(siteRoot, { recursive: true });

copyDirectory(path.join(workspaceRoot, 'apps', 'portal', 'public'), siteRoot);
copyDirectory(path.join(workspaceRoot, 'tools', 'platform-shell'), siteRoot);
copyDirectory(path.join(distRoot, 'showcases', 'angular'), path.join(siteRoot, 'showcases', 'angular'));
copyDirectory(path.join(distRoot, 'showcases', 'react'), path.join(siteRoot, 'showcases', 'react'));
copyDirectory(path.join(distRoot, 'showcases', 'vanilla'), path.join(siteRoot, 'showcases', 'vanilla'));

const docsRoot = path.join(siteRoot, 'docs');
mkdirSync(docsRoot, { recursive: true });
copyFile(path.join(workspaceRoot, 'apps', 'docs', 'public', 'styles.css'), path.join(docsRoot, 'styles.css'));
copyFile(path.join(workspaceRoot, 'apps', 'docs', 'public', 'search.js'), path.join(docsRoot, 'search.js'));

process.env.VRE_SINGLE_HOST = '1';
const documentationModuleUrl = `${pathToFileURL(path.join(distRoot, 'apps', 'docs', 'server.js')).href}?single-host=1`;
const { documentationSearchPayload, staticDocumentationPages } = await import(documentationModuleUrl);
const pages = staticDocumentationPages();

for (const page of pages) {
  const target = safeSitePath(page.path);
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, page.html, 'utf8');
}

const overview = pages.find(({ path: pagePath }) => pagePath === 'docs/overview/index.html');
if (!overview) {
  throw new Error('The documentation catalog does not contain the overview page.');
}
writeFileSync(path.join(docsRoot, 'index.html'), overview.html, 'utf8');
writeFileSync(path.join(docsRoot, 'search-index.json'), `${JSON.stringify(documentationSearchPayload())}\n`, 'utf8');

const hostedReportsRoot = path.join(siteRoot, 'reports');
copyOptionalDirectory(path.join(workspaceRoot, 'reports'), hostedReportsRoot);
injectPlatformConfig(hostedReportsRoot);

const automationRoot = path.join(siteRoot, 'automation');
mkdirSync(automationRoot, { recursive: true });
copyFile(path.join(workspaceRoot, 'apps', 'portal', 'public', 'playwright.html'), path.join(automationRoot, 'index.html'));
copyOptionalDirectory(path.join(workspaceRoot, 'artifacts', 'playwright'), path.join(automationRoot, 'artifacts'));

const publicBaseUrl = (process.env.VRE_PUBLIC_URL ?? '').replace(/\/$/, '');
const configuredUrls = {
  portal: publicBaseUrl,
  docs: publicBaseUrl,
  angular: `${publicBaseUrl}/showcases/angular`,
  react: `${publicBaseUrl}/showcases/react`,
  vanilla: `${publicBaseUrl}/showcases/vanilla`
};
const platformConfigSource = [
  '// Generated by tools/hosting/build-site.mjs for same-origin production hosting.',
  '(() => {',
  `  const configured = ${JSON.stringify(configuredUrls)};`,
  "  const currentOrigin = globalThis.location?.origin ?? '';",
  "  const resolveUrl = (value) => value ? new URL(value, currentOrigin + '/').href.replace(/\\/$/, '') : currentOrigin;",
  '  globalThis.vrePlatformConfig = globalThis.vrePlatformConfig || {',
  '    urls: Object.fromEntries(Object.entries(configured).map(([key, value]) => [key, resolveUrl(value)]))',
  '  };',
  '})();',
  ''
].join('\n');

for (const configPath of [
  path.join(siteRoot, 'platform-config.js'),
  path.join(siteRoot, 'showcases', 'angular', 'platform-config.js'),
  path.join(siteRoot, 'showcases', 'react', 'platform-config.js'),
  path.join(siteRoot, 'showcases', 'vanilla', 'platform-config.js')
]) {
  writeFileSync(configPath, platformConfigSource, 'utf8');
}

const packageVersion = JSON.parse(readFileSync(path.join(workspaceRoot, 'package.json'), 'utf8')).version;

writeFileSync(path.join(siteRoot, 'deployment-manifest.json'), `${JSON.stringify({
  version: packageVersion,
  routes: {
    portal: '/',
    documentation: '/docs/',
    angularShowcase: '/showcases/angular/',
    reactShowcase: '/showcases/react/',
    vanillaShowcase: '/showcases/vanilla/',
    reports: '/reports/',
    automation: '/automation/'
  }
}, null, 2)}\n`, 'utf8');

copyFile(
  path.join(workspaceRoot, 'tools', 'hosting', 'staticwebapp.config.json'),
  path.join(siteRoot, 'staticwebapp.config.json')
);

writeStaticHostingApis({
  version: packageVersion,
  urls: configuredUrls,
  publicBaseUrl
});

console.log(`Built the single-host site at ${siteRoot}`);
console.log(`Generated ${pages.length} documentation pages.`);

function safeSitePath(relativePath) {
  const resolved = path.resolve(siteRoot, relativePath);
  if (!resolved.startsWith(`${siteRoot}${path.sep}`)) {
    throw new Error(`Refusing to write outside the site directory: ${relativePath}`);
  }
  return resolved;
}

function copyDirectory(source, target) {
  mkdirSync(target, { recursive: true });
  cpSync(source, target, { recursive: true, force: true });
}

function copyOptionalDirectory(source, target) {
  if (existsSync(source)) {
    copyDirectory(source, target);
  }
}

function copyFile(source, target) {
  mkdirSync(path.dirname(target), { recursive: true });
  cpSync(source, target, { force: true });
}

function injectPlatformConfig(root) {
  if (!existsSync(root)) {
    return;
  }
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const target = path.join(root, entry.name);
    if (entry.isDirectory()) {
      injectPlatformConfig(target);
      continue;
    }
    if (!entry.isFile() || path.extname(entry.name) !== '.html') {
      continue;
    }
    const html = readFileSync(target, 'utf8');
    if (!html.includes('<validation-platform-shell') || html.includes('src="/platform-config.js"')) {
      continue;
    }
    writeFileSync(target, html.replace('<head>', '<head>\n  <script src="/platform-config.js"></script>'), 'utf8');
  }
}

function writeJson(relativePath, data) {
  const target = safeSitePath(relativePath);
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function writeStaticHostingApis({ version, urls, publicBaseUrl }) {
  const docsBase = publicBaseUrl || '';
  const applications = [
    {
      id: 'docs',
      title: 'Documentation',
      shortTitle: 'Docs',
      description: 'Concepts, guides, public APIs, architecture, testing, and migration guidance.',
      kind: 'documentation',
      url: `${docsBase}/docs/overview`,
      healthUrl: '/docs/health',
      startScript: 'serve:docs:portal',
      documentationUrl: `${docsBase}/docs/overview`,
      tags: ['Guides', 'API', 'Architecture'],
      state: 'healthy',
      detail: 'Served by the unified host'
    },
    {
      id: 'vanilla-showcase',
      title: 'Vanilla Showcase',
      shortTitle: 'Vanilla',
      description: 'Framework-free TypeScript forms that call @validation-rules-engine/core directly for simple, complex, and large-form validation.',
      kind: 'showcase',
      url: urls.vanilla,
      healthUrl: `${urls.vanilla}/health`,
      startScript: 'serve:static',
      documentationUrl: `${docsBase}/docs/core-package`,
      tags: ['TypeScript', 'Vite', 'Core API'],
      showcaseLinks: [
        ['Simple Form', 'simple'],
        ['Complex Form', 'complex'],
        ['Performance Form', 'performance']
      ].map(([label, slug]) => ({
        label,
        url: `${urls.vanilla}/${slug}`,
        documentationUrl: `${docsBase}/docs/core-examples`
      })),
      state: 'healthy',
      detail: 'Served by the unified host'
    },
    {
      id: 'angular-showcase',
      title: 'Angular Showcase',
      shortTitle: 'Angular',
      description: 'Angular validation showcases with UI framework examples and comparable state management implementations.',
      kind: 'showcase',
      url: urls.angular,
      healthUrl: `${urls.angular}/health`,
      startScript: 'serve:static',
      documentationUrl: `${docsBase}/docs/angular`,
      tags: ['ngModel', 'Reactive Forms', 'NgRx', 'NGXS', 'Signals'],
      showcaseLinks: [
        ['Template Driven', 'template-driven', 'angular-ngmodel'],
        ['Reactive Forms', 'reactive-forms', 'angular-reactive-forms'],
        ['NgRx', 'ngrx', 'angular-state-ngrx'],
        ['NGXS', 'ngxs', 'angular-state-ngxs'],
        ['Akita', 'akita', 'angular-state-akita'],
        ['Elf', 'elf', 'angular-state-elf'],
        ['RxAngular State', 'rx-angular-state', 'angular-state-rx-angular'],
        ['Signals', 'signals', 'angular-state-signals'],
        ['Custom RxJS Store', 'custom-rxjs-store', 'angular-state-custom-rxjs-store']
      ].map(([label, slug, docSlug]) => ({
        label,
        url: `${urls.angular}/state/${slug}`,
        documentationUrl: `${docsBase}/docs/${docSlug}`
      })),
      state: 'healthy',
      detail: 'Served by the unified host'
    },
    {
      id: 'react-showcase',
      title: 'React Showcase',
      shortTitle: 'React',
      description: 'Hooks-first controlled forms with nested policies, dynamic groups, accessibility, and measured large-form behavior.',
      kind: 'showcase',
      url: urls.react,
      healthUrl: `${urls.react}/health`,
      startScript: 'serve:static',
      documentationUrl: `${docsBase}/docs/react-overview`,
      tags: ['React', 'Hooks', 'Seven state integrations'],
      showcaseLinks: [
        ['Local State', 'local-state'],
        ['Redux Toolkit', 'redux-toolkit'],
        ['Zustand', 'zustand'],
        ['Jotai', 'jotai'],
        ['Recoil', 'recoil'],
        ['MobX', 'mobx'],
        ['Context API', 'context']
      ].map(([label, slug]) => ({
        label,
        url: `${urls.react}/state/${slug}`,
        documentationUrl: `${docsBase}/docs/react-state-${slug}`
      })),
      state: 'healthy',
      detail: 'Served by the unified host'
    }
  ];

  const revision = (process.env.GITHUB_SHA ?? process.env.VRE_REVISION ?? '').slice(0, 7) || 'local';
  const builtAt = process.env.VRE_BUILD_TIME ?? new Date().toISOString();

  writeJson('api/status.json', { applications });
  writeJson('api/meta.json', {
    version,
    revision,
    builtAt,
    repository: 'https://github.com/kalyan-k/validation-rules-engine',
    urls
  });
  writeJson('api/health.json', {
    status: 'healthy',
    service: 'portal',
    applications
  });
  writeJson('api/health-ready.json', {
    status: 'healthy',
    service: 'portal',
    applications
  });
  writeJson('api/docs-health.json', { status: 'healthy', service: 'documentation' });
  writeJson('api/angular-health.json', { status: 'healthy', service: 'angular-showcase' });
  writeJson('api/react-health.json', { status: 'healthy', service: 'react-showcase' });
  writeJson('api/vanilla-health.json', { status: 'healthy', service: 'vanilla-showcase' });

  const playwrightLatestSource = path.join(
    workspaceRoot,
    'artifacts',
    'playwright',
    'portal-data',
    'latest-run.json'
  );
  if (existsSync(playwrightLatestSource)) {
    copyFile(playwrightLatestSource, path.join(siteRoot, 'api', 'playwright', 'latest.json'));
  } else {
    writeJson('api/playwright/latest.json', {
      available: false,
      message: 'No Playwright report data is available yet.',
      command: 'npm run test:e2e:smoke'
    });
  }
}
