import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const workspaceRoot = process.cwd();
const distRoot = path.join(workspaceRoot, 'dist');
const siteRoot = path.join(distRoot, 'site');

if (path.dirname(siteRoot) !== distRoot || path.basename(siteRoot) !== 'site') {
  throw new Error(`Refusing to rebuild an unexpected site directory: ${siteRoot}`);
}

const requiredDirectories = [
  path.join(workspaceRoot, 'apps', 'portal', 'public'),
  path.join(workspaceRoot, 'apps', 'docs', 'public'),
  path.join(workspaceRoot, 'tools', 'platform-shell'),
  path.join(distRoot, 'apps', 'docs'),
  path.join(distRoot, 'showcases', 'angular'),
  path.join(distRoot, 'showcases', 'react')
];

for (const directory of requiredDirectories) {
  if (!existsSync(directory)) {
    throw new Error(`Required hosted application output is missing: ${directory}`);
  }
}

rmSync(siteRoot, { recursive: true, force: true });
mkdirSync(siteRoot, { recursive: true });

copyDirectory(path.join(workspaceRoot, 'apps', 'portal', 'public'), siteRoot);
copyDirectory(path.join(workspaceRoot, 'tools', 'platform-shell'), siteRoot);
copyDirectory(path.join(distRoot, 'showcases', 'angular'), path.join(siteRoot, 'showcases', 'angular'));
copyDirectory(path.join(distRoot, 'showcases', 'react'), path.join(siteRoot, 'showcases', 'react'));

const docsRoot = path.join(siteRoot, 'docs');
mkdirSync(docsRoot, { recursive: true });
copyFile(path.join(workspaceRoot, 'apps', 'docs', 'public', 'styles.css'), path.join(docsRoot, 'styles.css'));
copyFile(path.join(workspaceRoot, 'apps', 'docs', 'public', 'search.js'), path.join(docsRoot, 'search.js'));

process.env.VRE_SINGLE_HOST = '1';
const documentationModuleUrl = `${pathToFileURL(path.join(distRoot, 'apps', 'docs', 'server.js')).href}?single-host=1`;
const { documentationSearchPayload, staticDocumentationPages } = await import(documentationModuleUrl);
const pages = staticDocumentationPages();

for (const page of pages) {
  const target = safeSitePath(page.path);
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, page.html, 'utf8');
}

const overview = pages.find(({ path: pagePath }) => pagePath === 'docs/overview/index.html');
if (!overview) {
  throw new Error('The documentation catalog does not contain the overview page.');
}
writeFileSync(path.join(docsRoot, 'index.html'), overview.html, 'utf8');
writeFileSync(path.join(docsRoot, 'search-index.json'), `${JSON.stringify(documentationSearchPayload())}\n`, 'utf8');

const hostedReportsRoot = path.join(siteRoot, 'reports');
copyOptionalDirectory(path.join(workspaceRoot, 'reports'), hostedReportsRoot);
injectPlatformConfig(hostedReportsRoot);

const automationRoot = path.join(siteRoot, 'automation');
mkdirSync(automationRoot, { recursive: true });
copyFile(path.join(workspaceRoot, 'apps', 'portal', 'public', 'playwright.html'), path.join(automationRoot, 'index.html'));
copyOptionalDirectory(path.join(workspaceRoot, 'artifacts', 'playwright'), path.join(automationRoot, 'artifacts'));

const publicBaseUrl = (process.env.VRE_PUBLIC_URL ?? '').replace(/\/$/, '');
const configuredUrls = {
  portal: publicBaseUrl,
  docs: publicBaseUrl,
  angular: `${publicBaseUrl}/showcases/angular`,
  react: `${publicBaseUrl}/showcases/react`
};
const platformConfigSource = [
  '// Generated by tools/hosting/build-site.mjs for same-origin production hosting.',
  '(() => {',
  `  const configured = ${JSON.stringify(configuredUrls)};`,
  "  const currentOrigin = globalThis.location?.origin ?? '';",
  "  const resolveUrl = (value) => value ? new URL(value, currentOrigin + '/').href.replace(/\\/$/, '') : currentOrigin;",
  '  globalThis.vrePlatformConfig = globalThis.vrePlatformConfig || {',
  '    urls: Object.fromEntries(Object.entries(configured).map(([key, value]) => [key, resolveUrl(value)]))',
  '  };',
  '})();',
  ''
].join('\n');

for (const configPath of [
  path.join(siteRoot, 'platform-config.js'),
  path.join(siteRoot, 'showcases', 'angular', 'platform-config.js'),
  path.join(siteRoot, 'showcases', 'react', 'platform-config.js')
]) {
  writeFileSync(configPath, platformConfigSource, 'utf8');
}

writeFileSync(path.join(siteRoot, 'deployment-manifest.json'), `${JSON.stringify({
  version: JSON.parse(readFileSync(path.join(workspaceRoot, 'package.json'), 'utf8')).version,
  routes: {
    portal: '/',
    documentation: '/docs/',
    angularShowcase: '/showcases/angular/',
    reactShowcase: '/showcases/react/',
    reports: '/reports/',
    automation: '/automation/'
  }
}, null, 2)}\n`, 'utf8');

console.log(`Built the single-host site at ${siteRoot}`);
console.log(`Generated ${pages.length} documentation pages.`);

function safeSitePath(relativePath) {
  const resolved = path.resolve(siteRoot, relativePath);
  if (!resolved.startsWith(`${siteRoot}${path.sep}`)) {
    throw new Error(`Refusing to write outside the site directory: ${relativePath}`);
  }
  return resolved;
}

function copyDirectory(source, target) {
  mkdirSync(target, { recursive: true });
  cpSync(source, target, { recursive: true, force: true });
}

function copyOptionalDirectory(source, target) {
  if (existsSync(source)) {
    copyDirectory(source, target);
  }
}

function copyFile(source, target) {
  mkdirSync(path.dirname(target), { recursive: true });
  cpSync(source, target, { force: true });
}

function injectPlatformConfig(root) {
  if (!existsSync(root)) {
    return;
  }
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const target = path.join(root, entry.name);
    if (entry.isDirectory()) {
      injectPlatformConfig(target);
      continue;
    }
    if (!entry.isFile() || path.extname(entry.name) !== '.html') {
      continue;
    }
    const html = readFileSync(target, 'utf8');
    if (!html.includes('<validation-platform-shell') || html.includes('src="/platform-config.js"')) {
      continue;
    }
    writeFileSync(target, html.replace('<head>', '<head>\n  <script src="/platform-config.js"></script>'), 'utf8');
  }
}
